name = "cleanup-tracker-app"
compatibility_date = "2023-05-18"
pages_build_output_dir = "cleanup-tracker-app/client/build"

# Local development database
[[d1_databases]]
binding = "DB"
database_name = "cleanup-tracker-dev"
database_id = "local"

# Production database
[[d1_databases]]
binding = "DB"
database_name = "cleanup-tracker-prod"
database_id = "2b7f91f0-c409-4a4e-85a0-a35b4475af8c"